int _putchar(int c);
int _isupper(char ch);
int _isdigit(char ch);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int i);
void print_diagonal(int i);
void print_square(int i);
void print_triangle(int i);
