int _putchar(int c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(char ch);
int _isalpha(char ch);
int print_sign(int i);
int _abs(int i);
int print_last_digit(int i);
void jack_bauer(void);
void times_table(void);
int add(int a, int b);